import { useMemo } from 'react';
import { Card, CardContent, CardHeader } from '../components/ui/card';
import { Button } from '../components/ui/button';
import { PrivacyAmount } from '../components/PrivacyAmount';
import { TrendingUp, TrendingDown, Download, Zap } from 'lucide-react';
import { WalletChips } from '../components/WalletChips';
import { TrendChip } from '../components/TrendChip';
import { ErrorState, EmptyState, LoadingState } from '../components/ScreenStates';
import { motion, AnimatePresence } from 'motion/react';
import { AreaChart, Area, ResponsiveContainer, XAxis, YAxis, Tooltip, Legend } from 'recharts';
import { useTransactions, useRecentTransactions } from '@/hooks/useTransactions';
import { useBudgets } from '@/hooks/useBudgets';
import { useMonthFilter } from '@/hooks/useMonthFilter';
import { useWalletFilter } from '@/hooks/useWalletFilter';
import { useWallets } from '@/hooks/useWallets';
import { useAuth } from '@/hooks/useAuth';
import { useRecurringBills } from '@/hooks/useRecurringBills';
import { UpcomingBillsWidget } from '../components/UpcomingBillsWidget';
import { TextPositive, TextNegative, TextLink } from '../components/Markup';
import { getCategoryMeta } from '@/lib/categoryMetadata';
import { formatRupiah, cn, bgColorVar, textColorVar, borderColorVar, colorVar } from '@/lib/utils';
import { createCompactAxisFormatter } from '@/lib/chartFormatters';
import { format, startOfMonth, endOfMonth } from 'date-fns';
import { id as idLocale } from 'date-fns/locale';
import { pageEnter, fadeUp, useReducedMotion } from '@/lib/transitions';
import { useScreenState } from '@/hooks/useScreenState';
import { useFinancialHealthScore } from '@/hooks/data/useFinancialHealthScore';
import { useInsights } from '@/hooks/data/useInsights';
import { useFinancialHealth } from '@/hooks/data/useFinancialHealth';
import { useBudgetRecommendations } from '@/hooks/data/useBudgetRecommendations';
import { useAIInsights } from '@/hooks/data/useAIInsights';
import { BriefingCard } from '../components/BriefingCard';
import { AIInsightCard } from '../components/AIInsightCard';

function generatePDF(month: number, year: number, displayIncome: number, displayExpenses: number) {
  const monthName = format(new Date(year, month - 1), 'MMMM yyyy', { locale: idLocale });
  const balance = displayIncome - displayExpenses;

  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="UTF-8">
        <title>Gajian Aman - ${monthName}</title>
        <style>
          body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
          h1 { color: #4AE54A; margin-bottom: 10px; }
          .metrics { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 20px; margin: 30px 0; }
          .metric-box { border: 1px solid #ddd; padding: 20px; border-radius: 8px; }
          .metric-label { color: #999; font-size: 12px; margin-bottom: 8px; }
          .metric-value { font-size: 24px; font-weight: bold; color: #4AE54A; }
          .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #999; font-size: 12px; }
        </style>
      </head>
      <body>
        <h1>Gajian Aman</h1>
        <p>Monthly Report - ${monthName}</p>
        <div class="metrics">
          <div class="metric-box">
            <div class="metric-label">Pemasukan</div>
            <div class="metric-value">Rp ${(displayIncome / 1000000).toFixed(1)}jt</div>
          </div>
          <div class="metric-box">
            <div class="metric-label">Pengeluaran</div>
            <div class="metric-value">Rp ${(displayExpenses / 1000000).toFixed(1)}jt</div>
          </div>
          <div class="metric-box">
            <div class="metric-label">Saldo</div>
            <div class="metric-value">Rp ${(balance / 1000000).toFixed(1)}jt</div>
          </div>
        </div>
        <div class="footer">
          <p>Generated by Gajian Aman on ${format(new Date(), 'dd MMMM yyyy', { locale: idLocale })}</p>
        </div>
      </body>
    </html>
  `;

  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `Gajian-Aman-${monthName.replace(' ', '-')}.pdf`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// Format large numbers for compact display (KPI Strip)
function formatCompactRupiah(value: number): string {
  if (value >= 1000000) return `Rp ${(value / 1000000).toFixed(1)}jt`;
  if (value >= 1000) return `Rp ${(value / 1000).toFixed(0)}k`;
  return `Rp ${value}`;
}

// Format amounts for calendar cells
function formatCompact(amount: number): string {
  if (amount >= 1000000) return `${(amount / 1000000).toFixed(1)}jt`;
  if (amount >= 1000) return `${(amount / 1000).toFixed(0)}k`;
  return amount.toString();
}

// Build AI insight feed from multiple sources
interface InsightFeedItem {
  severity: 'critical' | 'warning' | 'info';
  emoji: string;
  title: string;
  body: string;
}

function buildInsightFeed(
  insights: ReturnType<typeof useInsights>,
  healthData: ReturnType<typeof useFinancialHealth>,
  budgetRecs: ReturnType<typeof useBudgetRecommendations>,
): InsightFeedItem[] {
  const items: InsightFeedItem[] = [];

  // Add anomalies (max 2)
  insights.anomalies.slice(0, 2).forEach((anomaly) => {
    items.push({
      severity: anomaly.severity === 'high' ? 'critical' : 'warning',
      emoji: '⚠️',
      title: anomaly.title,
      body: anomaly.description,
    });
  });

  // Add health insights (max 2)
  // healthData.insights is array of strings like "✅ Anda sangat disiplin..."
  healthData.insights?.slice(0, 2).forEach((insightText) => {
    const match = insightText.match(/^([\p{Emoji}]+)\s+(.+)$/u);
    if (match) {
      const [, emoji, text] = match;
      items.push({
        severity: 'info',
        emoji,
        title: 'Insight',
        body: text,
      });
    }
  });

  // Add first budget recommendation if space
  if (items.length < 4 && budgetRecs.length > 0) {
    const rec = budgetRecs[0];
    items.push({
      severity: rec.priority === 'critical' ? 'critical' : rec.priority === 'high' ? 'warning' : 'info',
      emoji: rec.isIncrease ? '📈' : '📉',
      title: rec.category,
      body: rec.reason,
    });
  }

  return items.slice(0, 4); // Max 4 items
}

export default function Overview() {
  const { user } = useAuth();
  const { month, year } = useMonthFilter();
  const { walletId, setWalletId } = useWalletFilter();
  const { wallets } = useWallets(user?.userId);
  const { transactions, income, expenses, isLoading, error } = useTransactions(month, year);
  const { transactions: recentTx } = useRecentTransactions(10);
  const { recurringBills, isLoading: billsLoading } = useRecurringBills();
  const { budgets } = useBudgets();
  const prefersReduced = useReducedMotion();

  // Screen state: loading, error, empty, or loaded
  const screenState = useScreenState({
    isLoading,
    error: error || null,
    isEmpty: transactions.length === 0,
  });

  // Feature 1: Health score and insights
  const healthScore = useFinancialHealthScore(transactions, budgets, month, year);
  const insights = useInsights(transactions, month, year);

  // Feature 2: Financial health and recommendations (for AI insight feed)
  const financialHealth = useFinancialHealth(transactions, budgets, month, year);
  const budgetRecs = useBudgetRecommendations(transactions, budgets, month, year);

  // Feature 3: AI-generated insights from backend API
  const { insights: aiInsights, loading: aiLoading } = useAIInsights(month, year);

  const filteredTransactions = walletId === 'all'
    ? transactions
    : transactions.filter((t) => t.wallet_id === walletId);

  const filteredIncome = filteredTransactions.filter((t) => t.type === 'income').reduce((s, t) => s + Number(t.amount), 0);
  const filteredExpenses = filteredTransactions.filter((t) => t.type === 'expense').reduce((s, t) => s + Number(t.amount), 0);

  const displayIncome = walletId === 'all' ? income : filteredIncome;
  const displayExpenses = walletId === 'all' ? expenses : filteredExpenses;
  const saldo = displayIncome - displayExpenses;

  // Previous month data for trend
  const prevMonth = month === 1 ? 12 : month - 1;
  const prevYear = month === 1 ? year - 1 : year;
  const { transactions: prevTransactions, income: prevIncome, expenses: prevExpenses } = useTransactions(prevMonth, prevYear);

  const prevFilteredIncome = walletId === 'all'
    ? prevIncome
    : prevTransactions.filter((t) => t.type === 'income' && t.wallet_id === walletId).reduce((s, t) => s + Number(t.amount), 0);

  // Daily budget calculation - safe-to-spend today
  const daysInMonth = useMemo(() => new Date(year, month, 0).getDate(), [month, year]);
  const currentDay = new Date().getDate();
  const daysRemaining = daysInMonth - currentDay + 1;
  const dailyBudget = useMemo(() => {
    const totalMonthlyBudget = budgets.reduce((sum, b) => sum + b.amount, 0);
    if (daysRemaining <= 0) return 0;
    const spent = filteredExpenses;
    const remaining = Math.max(0, totalMonthlyBudget - spent);
    return Math.floor(remaining / daysRemaining);
  }, [budgets, daysRemaining, filteredExpenses]);

  // Payday countdown
  const daysUntilPayday = useMemo(() => {
    if (!user?.payday_date) return null;
    const today = new Date().getDate();
    const payday = Number(user.payday_date);
    const daysLeft = payday >= today ? payday - today : daysInMonth - today + payday;
    return daysLeft;
  }, [user?.payday_date, currentDay, daysInMonth]);

  // Budget remaining percentage
  const totalBudget = useMemo(() => budgets.reduce((sum, b) => sum + b.amount, 0), [budgets]);
  const budgetRemainingPct = useMemo(() => {
    if (totalBudget <= 0) return null;
    return Math.round(((totalBudget - displayExpenses) / totalBudget) * 100);
  }, [totalBudget, displayExpenses]);

  // Highest-risk velocity category
  const topVelocity = useMemo(() => {
    return insights.velocities
      .filter(v => v.riskLevel !== 'safe')
      .sort((a, b) => b.percentUsed - a.percentUsed)[0] ?? null;
  }, [insights.velocities]);

  // Time-based greeting
  const greeting = useMemo(() => {
    const h = new Date().getHours();
    return h < 12 ? 'Selamat pagi' : h < 17 ? 'Selamat siang' : 'Selamat sore';
  }, []);

  // Calendar heatmap data by date
  const expenseByDate = useMemo(() => {
    const map: Record<string, number> = {};
    filteredTransactions
      .filter((t) => t.type === 'expense')
      .forEach((t) => {
        const dateStr = t.date.split('T')[0];
        map[dateStr] = (map[dateStr] || 0) + Number(t.amount);
      });
    return map;
  }, [filteredTransactions]);

  // Calendar grid data for heatmap
  const calendarDays = useMemo(() => {
    const firstDay = new Date(year, month - 1, 1);
    const startOffset = firstDay.getDay();
    const cells: Array<{ day: number | null; date: string; expense: number }> = [];

    // Empty cells before month starts
    for (let i = 0; i < startOffset; i++) {
      cells.push({ day: null, date: '', expense: 0 });
    }

    // Days of month
    for (let day = 1; day <= daysInMonth; day++) {
      const dateStr = `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
      cells.push({
        day,
        date: dateStr,
        expense: expenseByDate[dateStr] || 0,
      });
    }

    // Empty cells after month ends
    while (cells.length % 7 !== 0) {
      cells.push({ day: null, date: '', expense: 0 });
    }

    return cells;
  }, [year, month, daysInMonth, expenseByDate]);

  // Monthly chart data (simplified - 4 weeks)
  const monthlyChartData = useMemo(() => {
    const weeks = Array.from({ length: 4 }, (_, weekIdx) => {
      const start = startOfMonth(new Date(year, month - 1));
      const weekStart = new Date(start);
      weekStart.setDate(start.getDate() + weekIdx * 7);

      let income = 0, expense = 0;
      for (let i = 0; i < 7; i++) {
        const date = new Date(weekStart);
        date.setDate(weekStart.getDate() + i);
        const dateStr = format(date, 'yyyy-MM-dd');

        const txs = filteredTransactions.filter((t) => t.date === dateStr);
        income += txs.filter((t) => t.type === 'income').reduce((s, t) => s + Number(t.amount), 0);
        expense += txs.filter((t) => t.type === 'expense').reduce((s, t) => s + Number(t.amount), 0);
      }

      return {
        week: `W${weekIdx + 1}`,
        income,
        expense,
      };
    });
    return weeks;
  }, [filteredTransactions, month, year]);

  // Show error state if fetch failed
  if (screenState.error) {
    return (
      <ErrorState
        title="Gagal memuat dashboard"
        message={screenState.error.message || 'Terjadi kesalahan saat mengambil data. Silakan coba lagi.'}
        onRetry={() => window.location.reload()}
      />
    );
  }

  // Show loading state while fetching data
  if (screenState.isLoading) {
    return <LoadingState count={3} type="card" />;
  }

  // Show empty state if no transactions yet
  if (screenState.isEmpty) {
    return (
      <EmptyState
        title="Dashboard Kosong"
        message="Mulai dengan menambahkan transaksi pertama Anda untuk melihat ringkasan keuangan."
        actionLabel="Tambah Transaksi"
        onAction={() => (window.location.href = '/add-transaction')}
      />
    );
  }

  return (
    <motion.div
      initial={prefersReduced ? { opacity: 0 } : pageEnter.initial}
      animate={prefersReduced ? { opacity: 1 } : pageEnter.animate}
      transition={pageEnter.transition}
      className="space-y-6"
    >
      {/* Section 1: Compact Greeting Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className={cn('text-base font-semibold', textColorVar('content-primary'))}>
            {greeting}, {user?.name?.split(' ')[0] ?? 'Kamu'}
          </h2>
          <p className={cn('text-xs', textColorVar('content-tertiary'))}>
            {format(new Date(year, month - 1), 'MMMM yyyy', { locale: idLocale })}
          </p>
        </div>
        <Button
          type="button"
          size="icon"
          variant="ghost"
          onClick={() => generatePDF(month, year, displayIncome, displayExpenses)}
          aria-label="Export PDF"
          className={textColorVar('content-tertiary')}
        >
          <Download className="w-4 h-4" />
        </Button>
      </div>

      {/* Wallet Chips */}
      {wallets.length > 0 && (
        <WalletChips wallets={wallets} walletId={walletId} setWalletId={setWalletId} />
      )}

      {/* Section 3: "Sekilas Hari Ini" BriefingCards (3-col grid) */}
      <motion.div
        initial={prefersReduced ? { opacity: 0 } : { opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ staggerChildren: prefersReduced ? 0 : 0.05, delay: prefersReduced ? 0 : 0.1 }}
        className="grid grid-cols-3 gap-2.5"
      >
        {/* Card 1: Aman Hari Ini */}
        <motion.div
          initial={prefersReduced ? { opacity: 0 } : fadeUp.initial}
          animate={prefersReduced ? { opacity: 1 } : fadeUp.animate}
          transition={fadeUp.transition}
        >
          <BriefingCard
            icon={<Zap className="w-4 h-4" />}
            iconColorClass={cn('text-[var(--color-brand-primary)]')}
            label="Aman Hari Ini"
            value={<PrivacyAmount value={formatCompactRupiah(dailyBudget)} />}
            subtitle={`${daysRemaining} hari tersisa`}
            valueClassName={cn('font-mono', textColorVar('brand-primary'))}
          />
        </motion.div>

        {/* Card 2: Hari Gajian */}
        <motion.div
          initial={prefersReduced ? { opacity: 0 } : fadeUp.initial}
          animate={prefersReduced ? { opacity: 1 } : fadeUp.animate}
          transition={fadeUp.transition}
        >
          <BriefingCard
            icon={<TrendingUp className="w-4 h-4" />}
            iconColorClass={cn('text-[var(--color-sentiment-positive)]')}
            label="Hari Gajian"
            value={
              daysUntilPayday === null
                ? 'Belum diatur'
                : daysUntilPayday === 0
                  ? 'Besok!'
                  : `${daysUntilPayday} hari lagi`
            }
            subtitle="Ke depan"
            valueClassName={cn('font-semibold', daysUntilPayday && daysUntilPayday <= 3 ? 'text-[var(--color-brand-primary)]' : '')}
          />
        </motion.div>

        {/* Card 3: Sisa Budget */}
        <motion.div
          initial={prefersReduced ? { opacity: 0 } : fadeUp.initial}
          animate={prefersReduced ? { opacity: 1 } : fadeUp.animate}
          transition={fadeUp.transition}
        >
          <BriefingCard
            icon={<TrendingDown className="w-4 h-4" />}
            iconColorClass={cn(
              budgetRemainingPct !== null && budgetRemainingPct < 20
                ? 'text-[var(--color-sentiment-negative)]'
                : 'text-[var(--color-sentiment-positive)]'
            )}
            label="Sisa Budget"
            value={budgetRemainingPct !== null ? `${Math.max(0, budgetRemainingPct)}%` : '—'}
            subtitle="Bulan ini"
            valueClassName={cn('font-mono font-bold')}
          />
        </motion.div>
      </motion.div>

      {/* Section 4: KPI Strip (4-col horizontal) */}
      <motion.div
        initial={prefersReduced ? { opacity: 0 } : fadeUp.initial}
        animate={prefersReduced ? { opacity: 1 } : fadeUp.animate}
        transition={fadeUp.transition}
        className={cn('grid grid-cols-4 divide-x', borderColorVar('divide-neutral'))}
      >
        {/* KPI 1: Saldo */}
        <div className={cn('px-3 py-2.5', textColorVar('content-primary'))}>
          <p className={cn('text-[10px] font-medium mb-1 uppercase', textColorVar('content-tertiary'))}>Saldo</p>
          <p className={cn('text-sm font-mono font-bold')}>
            <PrivacyAmount value={formatCompactRupiah(saldo)} />
          </p>
        </div>

        {/* KPI 2: Pemasukan */}
        <div className={cn('px-3 py-2.5')}>
          <p className={cn('text-[10px] font-medium mb-1 uppercase', textColorVar('content-tertiary'))}>Pemasukan</p>
          <p className={cn('text-sm font-mono font-bold', textColorVar('sentiment-positive'))}>
            <PrivacyAmount value={formatCompactRupiah(displayIncome)} />
          </p>
        </div>

        {/* KPI 3: Pengeluaran */}
        <div className={cn('px-3 py-2.5')}>
          <p className={cn('text-[10px] font-medium mb-1 uppercase', textColorVar('content-tertiary'))}>Pengeluaran</p>
          <p className={cn('text-sm font-mono font-bold', textColorVar('sentiment-negative'))}>
            <PrivacyAmount value={formatCompactRupiah(displayExpenses)} />
          </p>
        </div>

        {/* KPI 4: Hari Tersisa */}
        <div className={cn('px-3 py-2.5', textColorVar('content-primary'))}>
          <p className={cn('text-[10px] font-medium mb-1 uppercase', textColorVar('content-tertiary'))}>Hari Tersisa</p>
          <p className={cn('text-sm font-mono font-bold')}>{daysRemaining}</p>
        </div>
      </motion.div>

      {/* Section 5.5: Compact Calendar Heatmap */}
      <motion.div
        initial={prefersReduced ? { opacity: 0 } : fadeUp.initial}
        animate={prefersReduced ? { opacity: 1 } : fadeUp.animate}
        transition={fadeUp.transition}
      >
        <Card className={cn(bgColorVar('bg-card'), borderColorVar('border-neutral'))}>
          <CardHeader>
            <h3 className={cn('text-base font-semibold', textColorVar('content-primary'))}>Pengeluaran Per Hari</h3>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-7 gap-0.5">
              {['Min', 'Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab'].map((d) => (
                <div key={d} className={cn('text-center text-[10px] py-1 font-semibold', textColorVar('content-tertiary'))}>
                  {d}
                </div>
              ))}
              {calendarDays.map((cell, i) => {
                const getHeatColor = (amount: number) => {
                  if (amount === 0) return bgColorVar('bg-neutral');
                  if (amount <= 50_000) return 'bg-green-100 dark:bg-green-900/30';
                  if (amount <= 200_000) return 'bg-yellow-100 dark:bg-yellow-900/30';
                  if (amount <= 500_000) return 'bg-orange-100 dark:bg-orange-900/30';
                  return 'bg-red-100 dark:bg-red-900/30';
                };

                const isTodayColor = cell.day === new Date().getDate() && new Date().getMonth() === month - 1 && new Date().getFullYear() === year
                  ? 'border-[var(--color-brand-primary)] border-2'
                  : borderColorVar('border-neutral') + ' border';

                return (
                  <div
                    key={i}
                    className={cn(
                      'h-8 rounded-sm p-0.5 relative flex items-center justify-center',
                      cell.day ? getHeatColor(cell.expense) : 'bg-transparent',
                      isTodayColor
                    )}
                    title={cell.day ? `${formatRupiah(cell.expense)}` : ''}
                  >
                    {cell.day && (
                      <>
                        <span className={cn('text-[10px] font-semibold', textColorVar('content-primary'))}>
                          {cell.day}
                        </span>
                        {cell.expense > 0 && (
                          <span className={cn('text-[7px] absolute bottom-0.5 right-0.5 font-mono', textColorVar('content-tertiary'))}>
                            {formatCompact(cell.expense)}
                          </span>
                        )}
                      </>
                    )}
                  </div>
                );
              })}
            </div>
          </CardContent>
        </Card>
      </motion.div>

      {/* Section 5: AI Insight Feed */}
      <motion.div
        initial={prefersReduced ? { opacity: 0 } : fadeUp.initial}
        animate={prefersReduced ? { opacity: 1 } : fadeUp.animate}
        transition={fadeUp.transition}
      >
        <Card className={cn(bgColorVar('bg-card'), borderColorVar('border-neutral'))}>
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <h3 className={cn('text-base font-semibold', textColorVar('content-primary'))}>AI Insight</h3>
              <span className={cn('text-xs font-semibold px-2 py-1 rounded', 'bg-[var(--color-brand-primary)]/10', textColorVar('brand-primary'))}>
                {healthScore.score}/100
              </span>
            </div>
          </CardHeader>
          <CardContent className="space-y-2">
            {/* Show loading state while fetching API insights */}
            {aiLoading && aiInsights.length === 0 ? (
              <div className={cn('text-xs text-center py-3 animate-pulse', textColorVar('content-tertiary'))}>
                Menganalisis transaksi Anda...
              </div>
            ) : aiInsights.length > 0 ? (
              // Use API-generated insights (preferred)
              <AnimatePresence>
                {aiInsights.map((item, idx) => (
                  <AIInsightCard
                    key={`ai-${item.severity}-${idx}`}
                    severity={item.severity}
                    emoji={item.emoji}
                    title={item.title}
                    body={item.body}
                    prefersReduced={prefersReduced}
                    delay={prefersReduced ? 0 : idx * 0.08}
                  />
                ))}
              </AnimatePresence>
            ) : buildInsightFeed(insights, financialHealth, budgetRecs).length > 0 ? (
              // Fallback to client-side calculated insights
              <AnimatePresence>
                {buildInsightFeed(insights, financialHealth, budgetRecs).map((item, idx) => (
                  <AIInsightCard
                    key={`fallback-${item.severity}-${idx}`}
                    severity={item.severity}
                    emoji={item.emoji}
                    title={item.title}
                    body={item.body}
                    prefersReduced={prefersReduced}
                    delay={prefersReduced ? 0 : idx * 0.08}
                  />
                ))}
              </AnimatePresence>
            ) : (
              // Empty state
              <p className={cn('text-xs text-center py-3', textColorVar('content-tertiary'))}>
                Tambah lebih banyak transaksi untuk mendapatkan rekomendasi AI
              </p>
            )}
          </CardContent>
        </Card>
      </motion.div>

      {/* Desktop: Chart + Upcoming Bills | Mobile: Full-width Chart */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Chart - 2 columns on desktop, 1 on mobile */}
        <motion.div
          initial={prefersReduced ? { opacity: 0 } : fadeUp.initial}
          animate={prefersReduced ? { opacity: 1 } : fadeUp.animate}
          transition={fadeUp.transition}
          className="lg:col-span-2"
        >
          <Card className={cn(bgColorVar('bg-card'), borderColorVar('border-neutral'))}>
            <CardHeader>
              <h3 className={cn('text-base font-semibold', textColorVar('content-primary'))}>Income vs Expense</h3>
            </CardHeader>
            <CardContent>
              {monthlyChartData.some(d => d.income > 0 || d.expense > 0) ? (
                <ResponsiveContainer width="100%" height={220}>
                  <AreaChart data={monthlyChartData}>
                    <defs>
                      <linearGradient id="colorIncome" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor="var(--color-sentiment-positive)" stopOpacity={0.3} />
                        <stop offset="95%" stopColor="var(--color-sentiment-positive)" stopOpacity={0} />
                      </linearGradient>
                      <linearGradient id="colorExpense" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor="var(--color-sentiment-negative)" stopOpacity={0.3} />
                        <stop offset="95%" stopColor="var(--color-sentiment-negative)" stopOpacity={0} />
                      </linearGradient>
                    </defs>
                    <XAxis dataKey="week" stroke="var(--color-content-tertiary)" fontSize={12} />
                    <YAxis stroke="var(--color-content-tertiary)" fontSize={12} tickFormatter={createCompactAxisFormatter()} />
                    <Tooltip
                      formatter={(value: number) => formatRupiah(value)}
                      contentStyle={{ backgroundColor: 'var(--color-bg-elevated)', border: '1px solid var(--color-border-neutral)' }}
                    />
                    <Legend />
                    <Area type="monotone" dataKey="income" stroke="var(--color-sentiment-positive)" strokeWidth={2} fill="url(#colorIncome)" name="Income" isAnimationActive={!prefersReduced} />
                    <Area type="monotone" dataKey="expense" stroke="var(--color-sentiment-negative)" strokeWidth={2} fill="url(#colorExpense)" name="Expense" isAnimationActive={!prefersReduced} />
                  </AreaChart>
                </ResponsiveContainer>
              ) : (
                <p className={cn('text-sm text-center py-8', textColorVar('content-tertiary'))}>Belum ada data bulan ini</p>
              )}
            </CardContent>
          </Card>
        </motion.div>

        {/* Upcoming Bills - 1 column on desktop */}
        <motion.div
          initial={prefersReduced ? { opacity: 0 } : fadeUp.initial}
          animate={prefersReduced ? { opacity: 1 } : fadeUp.animate}
          transition={fadeUp.transition}
        >
          <UpcomingBillsWidget recurringBills={recurringBills} isLoading={billsLoading} />
        </motion.div>
      </div>

      {/* Recent Transactions */}
      <motion.div
        initial={prefersReduced ? { opacity: 0 } : fadeUp.initial}
        animate={prefersReduced ? { opacity: 1 } : fadeUp.animate}
        transition={fadeUp.transition}
      >
        <Card className={cn(bgColorVar('bg-card'), borderColorVar('border-neutral'))}>
          <CardHeader>
            <h3 className={cn('text-base font-semibold', textColorVar('content-primary'))}>Transaksi Terbaru</h3>
          </CardHeader>
          <CardContent>
            {recentTx.length === 0 ? (
              <p className={cn('text-sm text-center py-4', textColorVar('content-tertiary'))}>Belum ada transaksi</p>
            ) : (
              <div className="space-y-2">
                <AnimatePresence>
                  {recentTx.slice(0, 5).map((tx, idx) => {
                    const meta = getCategoryMeta(tx.category);
                    return (
                      <motion.div
                        key={tx.id}
                        initial={prefersReduced ? { opacity: 0 } : { opacity: 0, y: 8 }}
                        animate={prefersReduced ? { opacity: 1 } : { opacity: 1, y: 0 }}
                        transition={{ delay: prefersReduced ? 0 : idx * 0.05 }}
                        className={cn('flex items-center justify-between p-2.5 rounded-lg border', bgColorVar('bg-screen'), borderColorVar('border-neutral'))}
                      >
                        <div className="flex items-center gap-3 flex-1 min-w-0">
                          <span className="text-lg flex-shrink-0">{meta.emoji}</span>
                          <div className="min-w-0">
                            <p className={cn('text-sm font-medium truncate', textColorVar('content-primary'))}>{tx.note || tx.category}</p>
                            <p className={cn('text-xs', textColorVar('content-tertiary'))}>{format(new Date(tx.date), 'dd MMM', { locale: idLocale })}</p>
                          </div>
                        </div>
                        <div className="font-mono font-semibold text-sm flex-shrink-0 ml-2">
                          {tx.type === 'income' ? (
                            <TextPositive>
                              +<PrivacyAmount value={formatRupiah(Number(tx.amount))} />
                            </TextPositive>
                          ) : (
                            <TextNegative>
                              −<PrivacyAmount value={formatRupiah(Number(tx.amount))} />
                            </TextNegative>
                          )}
                        </div>
                      </motion.div>
                    );
                  })}
                </AnimatePresence>
              </div>
            )}
            {recentTx.length > 5 && (
              <div className="mt-4 text-center">
                <a href="/riwayat" className="text-sm">
                  <TextLink>Lihat semua →</TextLink>
                </a>
              </div>
            )}
          </CardContent>
        </Card>
      </motion.div>
    </motion.div>
  );
}
