/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UiKitRouteImport } from './routes/ui-kit'
import { Route as Dashboard3RouteImport } from './routes/dashboard-3'
import { Route as Dashboard2RouteImport } from './routes/dashboard-2'
import { Route as Dashboard1RouteImport } from './routes/dashboard-1'
import { Route as IndexRouteImport } from './routes/index'

const UiKitRoute = UiKitRouteImport.update({
  id: '/ui-kit',
  path: '/ui-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const Dashboard3Route = Dashboard3RouteImport.update({
  id: '/dashboard-3',
  path: '/dashboard-3',
  getParentRoute: () => rootRouteImport,
} as any)
const Dashboard2Route = Dashboard2RouteImport.update({
  id: '/dashboard-2',
  path: '/dashboard-2',
  getParentRoute: () => rootRouteImport,
} as any)
const Dashboard1Route = Dashboard1RouteImport.update({
  id: '/dashboard-1',
  path: '/dashboard-1',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard-1': typeof Dashboard1Route
  '/dashboard-2': typeof Dashboard2Route
  '/dashboard-3': typeof Dashboard3Route
  '/ui-kit': typeof UiKitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard-1': typeof Dashboard1Route
  '/dashboard-2': typeof Dashboard2Route
  '/dashboard-3': typeof Dashboard3Route
  '/ui-kit': typeof UiKitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard-1': typeof Dashboard1Route
  '/dashboard-2': typeof Dashboard2Route
  '/dashboard-3': typeof Dashboard3Route
  '/ui-kit': typeof UiKitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard-1' | '/dashboard-2' | '/dashboard-3' | '/ui-kit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard-1' | '/dashboard-2' | '/dashboard-3' | '/ui-kit'
  id:
    | '__root__'
    | '/'
    | '/dashboard-1'
    | '/dashboard-2'
    | '/dashboard-3'
    | '/ui-kit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Dashboard1Route: typeof Dashboard1Route
  Dashboard2Route: typeof Dashboard2Route
  Dashboard3Route: typeof Dashboard3Route
  UiKitRoute: typeof UiKitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ui-kit': {
      id: '/ui-kit'
      path: '/ui-kit'
      fullPath: '/ui-kit'
      preLoaderRoute: typeof UiKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-3': {
      id: '/dashboard-3'
      path: '/dashboard-3'
      fullPath: '/dashboard-3'
      preLoaderRoute: typeof Dashboard3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-2': {
      id: '/dashboard-2'
      path: '/dashboard-2'
      fullPath: '/dashboard-2'
      preLoaderRoute: typeof Dashboard2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-1': {
      id: '/dashboard-1'
      path: '/dashboard-1'
      fullPath: '/dashboard-1'
      preLoaderRoute: typeof Dashboard1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Dashboard1Route: Dashboard1Route,
  Dashboard2Route: Dashboard2Route,
  Dashboard3Route: Dashboard3Route,
  UiKitRoute: UiKitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
