export const COPY = {
  emptyStates: {
    transactions: 'Belum ada transaksi. Yuk catat yang pertama!',
    budget: 'Budget belum dibuat. Atur sekarang biar keuangan lebih terarah.',
    goals: 'Belum ada goals. Mulai tentukan target finansialmu!',
    wallets: 'Belum ada wallet. Tambah sumber dana kamu dulu ya.',
    splitBill: 'Belum ada sesi split bill. Yuk mulai yang pertama!',
    history: 'Belum ada riwayat transaksi bulan ini.',
  },
  success: {
    transactionAdded: '✅ Transaksi berhasil dicatat!',
    budgetSaved: 'Budget disimpan. Semangat nabung!',
    goalCreated: 'Goal baru dibuat. You got this! 💪',
    walletCreated: 'Wallet berhasil ditambahkan!',
    splitBillCreated: 'Split bill berhasil dibuat. Bagikan linknya ke temen-temen!',
    goalFunded: (name: string, amount: string) => `+${amount} ditambahkan ke "${name}" 🎉`,
  },
  errors: {
    generic: 'Ups, ada yang error nih. Coba lagi ya.',
    noConnection: 'Koneksi terputus. Cek internet kamu dulu.',
    sessionExpired: 'Sesimu habis. Login lagi yuk.',
    invalidAmount: 'Nominalnya gak valid nih. Coba isi lagi ya.',
    notFound: 'Data tidak ditemukan.',
  },
  labels: {
    income: 'Pemasukan',
    expense: 'Pengeluaran',
    savings: 'Tabungan',
    budget: 'Anggaran',
    remaining: 'Sisa',
    spent: 'Terpakai',
    overview: 'Ringkasan',
    history: 'Riwayat',
    trends: 'Tren',
    goals: 'Tujuan',
    calendar: 'Kalender',
    splitBill: 'Split Bill',
    payday: 'Gajian',
    wallet: 'Dompet',
    subscription: 'Langganan',
    save: 'Simpan',
    cancel: 'Batal',
    add: 'Tambah',
    edit: 'Edit',
    delete: 'Hapus',
  },
  status: {
    safe: 'Aman',
    warning: 'Hampir',
    over: 'Melebihi',
    notSet: 'Belum Dibuat',
    achieved: 'Tercapai 🎉',
    inProgress: 'Jalan terus',
    deadlinePassed: 'Deadline Terlewat',
  },
} as const;
